### ISSUE TITLE
cant run yo jquery-boilerplate

### ISSUE THREAD

**Issue by astroanu** [jquery-boilerplate/generator-jquery-boilerplate#11]
i'm getting this..  tried re installing jquery-boilerplate,  clearing cache

  var files   = this.expandFiles('**/*', { cwd: this.sourceRoot(), dot: true }
                                                     ^
TypeError: Object [object Object] has no method 'sourceRoot'

**Comment by astroanu** [comment]
fullstop

**Comment by rodacato** [comment]
+1

**Comment by cameronjroe** [comment]
I opened a PR for this - should be working now.

**Comment by heldr** [comment]
@cameronjroe thanks!

No, I am going to limit it for 0.10.
